name: Validate PR Submission

on:
  pull_request:
    paths:
      - 'submissions/**'

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout PR
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
    
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v40
      with:
        files: |
          submissions/**/*.json
          submissions/**/*.yaml
          submissions/**/*.yml
        files_ignore: |
          submissions/.gitkeep
    
    - name: Validate submissions
      run: |
        # Exit code tracking
        exit_code=0
        
        # Check if any submission files were added/modified
        if [ -z "${{ steps.changed-files.outputs.all_changed_files }}" ]; then
          echo "❌ No submission files found in this PR"
          echo "Please add your submission file to the 'submissions/' directory"
          exit 1
        fi
        
        # Validate each changed file
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "Validating: $file"
          
          # Run validation script
          if python scripts/validate_submission.py "$file"; then
            echo "✅ $file passed validation"
          else
            echo "❌ $file failed validation"
            exit_code=1
          fi
          
          echo "---"
        done
        
        # Check file naming convention
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          filename=$(basename "$file")
          # Ensure filename doesn't contain spaces or special characters
          if [[ ! "$filename" =~ ^[a-zA-Z0-9_.-]+\.(json|yaml|yml)$ ]]; then
            echo "❌ Invalid filename: $filename"
            echo "Filenames must only contain letters, numbers, underscores, hyphens, and dots"
            exit_code=1
          fi
        done
        
        exit $exit_code
    
    - name: Comment PR
      uses: actions/github-script@v7
      if: failure()
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '❌ Validation failed! Please check the workflow logs for details.\n\nMake sure your submission:\n- Is placed in the `submissions/` directory\n- Is a valid JSON or YAML file\n- Contains all required fields: `username`, `paper_title`, `paper_pdf`, `identifier`, `code_url`, `claims`\n- Has at least one claim with instructions\n- Has a valid filename (letters, numbers, underscores, hyphens only)'
          })
    
    - name: Comment PR Success
      uses: actions/github-script@v7
      if: success()
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '✅ All validations passed! Your submission is ready for review.'
          })